### ISSUE TITLE
Input Image

### ISSUE THREAD

**Issue by 94maldini** [viniciusgdr/imagemaker.js#1]
how to enter a file or image url?
```javascript
new Maker().PhotoOxy('https://photooxy.com/create-a-photo-frame-with-plastic-wrap-409.html', ["Image"]).then(res => {
    console.log(res)
})
``` 
I've tried but can't, I use this link https://photooxy.com/create-a-photo-frame-with-plastic-wrap-409.html

**Comment by AbroCode** [comment]
Please does this still work
